### ISSUE TITLE
Cookie popup so can add LinkedIn tracking

### ISSUE THREAD

**Issue by scholar6admin** [Scholar-6/brillder#2821]
#Updated task

var _mtm = _mtm || []; // make sure that _mtm is initialised in case Matomo script has not yet loaded.

When cookie pop-up is clicked or login
_mtm.push({"event": "start-tracking"}); 
_mtm.push({'tracking-enabled': true});

When stop tracking button or logout
_mtm.push({"event": "stop-tracking"}); 
_mtm.push({'tracking-enabled': false});

When synthesis signup 
_mtm.push({"event": "synthesis-signup"});

__________

- [x] Check if user already has a _redistest etc cookie before showing popup. 
- [x] Check updated text text
- [x] And make sure that zendesk widget is clickable

- [x] Simple white popup with blue text below and grey and red buttons - show me a screenshot and I'll let you know if adjustments needed

We need a popup that requires acceptance from new unauthenticated users, we also need a button in the bottom right to clear cookies and force the popup again. The zendesk widget should still be available while popup is active.
This does not apply to authenticated users because they will have accepted the user agreement.

As a new (no session cookies) unauthenticated user
When I visit any page except the login/signup/terms pages
Then I should see a popup that has to be accepted 
in order to preview bricks etc. 
Only after accepting the popup will the tag manager 
code be executed

The message in the popup should say:
```
We Use Cookies
If we had a market stall we would ask you where you are from and where you are going. We don't have a market stall, so we are asking if we can put some cookies in your browser that track how you found us and if you decide to come back. If you accept, then change your mind, you can push the button in the bottom right to 'stop tracking'. If you want all records of your visit to be deleted, you can send us a message at support@scholar6.org.
Accept Cookies
(Link to /terms)
```
Technical
If no session cookie (i.e. unauthenticated) AND not on login/signup page -> then display popup
If pop up accepted -> then make request to API that sets cookies and run the tag manager script. 
If 'stop tracking' button is pressed -> then clear cookies, force popup again, and stop any page analytics. 

```
<!-- Matomo Tag Manager -->
<script type="text/javascript">
var _mtm = window._mtm = window._mtm || [];
_mtm.push({'mtm.startTime': (new Date().getTime()), 'event': 'mtm.Start'});
var d=document, g=d.createElement('script'), s=d.getElementsByTagName('script')[0];
g.type='text/javascript'; g.async=true; g.src='https://matomo.brillder.com/js/container_UkdV64XH.js'; s.parentNode.insertBefore(g,s);
</script>
<!-- End Matomo Tag Manager -->
```

**Comment by ivanromakh** [comment]
@lindsaymacvean what do you mean by link to terms. if he is not logged in and in dashboard page shouldn`t he start playing? How user will go back to the dashboard from terms page?
![image](https://user-images.githubusercontent.com/18567511/108839372-ac11c500-75dd-11eb-911b-db6fc6aff660.png)

**Comment by ivanromakh** [comment]
@scholar6admin popup will look like this.
![image](https://user-images.githubusercontent.com/18567511/108839962-5e498c80-75de-11eb-9a5b-06a48d8a4cbc.png)

**Comment by ivanromakh** [comment]
@scholar6admin I don`t know how to make zendesk button clickable when popup is open now. I will think about it.
